### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PushkarOP** [fredi-python/ClipDropSDXL#1]
img) root@v754205187:~# python3 -m ClipDropSDXL --headless --prompt "golden retriever" --style neonpunk
/root/img/lib/python3.10/site-packages/ClipDropSDXL.py:34: DeprecationWarning: headless property is deprecated, instead use add_argument('--headless') or add_argument('--headless=new')
  options.headless = args.headless
The version of chrome cannot be detected. Trying with latest driver version
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/img/lib/python3.10/site-packages/ClipDropSDXL.py", line 110, in <module>
    main()
  File "/root/img/lib/python3.10/site-packages/ClipDropSDXL.py", line 37, in main
    driver = webdriver.Chrome(options=options)
  File "/root/img/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 49, in __init__
    super().__init__(
  File "/root/img/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 54, in __init__
    super().__init__(
  File "/root/img/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/root/img/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/root/img/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/root/img/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /snap/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55746e2b84e3 <unknown>
#1 0x55746dfe7c76 <unknown>
#2 0x55746e010d78 <unknown>
#3 0x55746e00d029 <unknown>
#4 0x55746e04bccc <unknown>
#5 0x55746e04b47f <unknown>
#6 0x55746e042de3 <unknown>
#7 0x55746e0182dd <unknown>
#8 0x55746e01934e <unknown>
#9 0x55746e2783e4 <unknown>
#10 0x55746e27c3d7 <unknown>
#11 0x55746e286b20 <unknown>
#12 0x55746e27d023 <unknown>
#13 0x55746e24b1aa <unknown>
#14 0x55746e2a16b8 <unknown>
#15 0x55746e2a1847 <unknown>
#16 0x55746e2b1243 <unknown>
#17 0x7f3c6f32ab43 <unknown>

**Comment by fredi-python** [comment]
Hey! Thanks for reporting this.
What browser do you have installed?

**Comment by PushkarOP** [comment]
> 

I am running it on ubuntu vps
And i install chromium using command: sudo apt install chromium-browser

**Comment by fredi-python** [comment]
Could you try it with firefox?

**Comment by PushkarOP** [comment]
> Could you try it with firefox?

root@v754205187:~# python3 -m ClipDropSDXL --headless --prompt "golden retriever" --style neonpunk
/usr/local/lib/python3.10/dist-packages/ClipDropSDXL.py:34: DeprecationWarning: headless property is deprecated, instead use add_argument('-headless')
  options.headless = args.headless
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/ClipDropSDXL.py", line 110, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/ClipDropSDXL.py", line 44, in main
    WebDriverWait(driver, 20).until(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:187:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:505:5
element.find/</<@chrome://remote/content/marionette/element.sys.mjs:135:16

**Comment by fredi-python** [comment]
Would you mind trying it with:
```
python3 -m ClipDropSDXL --headless --prompt "golden retriever" --style neonpunk --browser firefox
```
